# Generated by Django 5.1.7 on 2025-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='port',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
